version: 1
datastore:
  filename: /data/health/health_status.json
scheduler:
  interval: 20
timeout: 5
services:
  receiver: http://nginx:80/receiver/health  # Check through nginx load balancer
  storage: http://storage:8090/storage/health
  processing: http://processing:8100/processing/health
  analyzer: http://analyzer:8110/analyzer/health