services:
  zookeeper:
    image: zookeeper:3.7
    expose:
      - "2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=localhost:2888:3888;2181
    volumes:
      - zookeeper_data:/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: wurstmeister/kafka:latest
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_BROKER_ID: 1
    volumes:
      - ./data/kafka:/kafka  
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - kafka-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: skibidi
      MYSQL_PASSWORD: helpme
      MYSQL_DATABASE: fire_data
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Lab 12
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dashboard:/usr/share/nginx/html:ro
    depends_on:
      - receiver
      - storage
      - processing
      - analyzer
    networks:
      - kafka-network
    restart: on-failure
  

  receiver:
    build:
      context: ./receiver
      dockerfile: Dockerfile
    expose:
      - "8080"
    deploy:
      replicas: 3
    environment:
      CORS_ALLOW_ALL: "no"
    volumes:
      - ./logs:/logs
      - ./config/receiver:/config
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
    restart: on-failure

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    expose:
      - "8090"
    environment:
      CORS_ALLOW_ALL: "no"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/logs
      - ./data/storage:/data
      - ./config/storage:/config
    networks:
      - kafka-network
    restart: on-failure

  processing:
    build:
      context: ./processing
      dockerfile: Dockerfile
    expose:
      - "8100"
    environment:
      CORS_ALLOW_ALL: "no"
    depends_on:
      storage:
        condition: service_started
    volumes:
      - ./logs:/logs
      - ./data/processing:/data/processing
      - ./config/processing:/config
    networks:
      - kafka-network
    restart: on-failure

  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    expose:
      - "8110"
    environment:
      CORS_ALLOW_ALL: "no"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/logs
      - ./data/events:/data
      - ./config/analyzer:/config
    networks:
      - kafka-network
    restart: on-failure

  health:
    build:
      context: ./health
      dockerfile: Dockerfile
    expose:
      - "8120"
    environment:
      CORS_ALLOW_ALL: "no"
    volumes:
      - ./logs:/logs
      - ./data/health:/data/health
      - ./config/health:/config
    depends_on:
      - receiver
      - storage
      - processing
      - analyzer
    networks:
      - kafka-network
    restart: on-failure

volumes:
  mysql_data:
  zookeeper_data:

networks:
  kafka-network:
    driver: bridge