version: 1
datastore:
  filename: /data/check/check_status.json
scheduler:
  interval: 20 
timeout: 5  
services:
  receiver: http://receiver/receiver/check
  storage: http://storage/storage/stats
  processing: http://processing/processing/stats
  analyzer: http://analyzer/analyzer/stats