version: 1
datastore:
  filename: /data/processing/data.json
scheduler:
  interval: 5
eventstores:
  temperature:
    url: http://storage:8090/storage/temperature
  airquality:
    url: http://storage:8090/storage/airquality
